language: python
python:
  - "2.7"
  - "3.4"
install:
  - "python setup.py install"
  - "pip install -r test-requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
script: coverage run setup.py test
after_success:
  coveralls